name = "InterferometricModels"
uuid = "b395d269-c2ec-4df6-b679-36919ad600ca"
authors = ["Alexander Plavin <alexander@plav.in>"]
version = "0.1.30"

[deps]
AccessorsExtra = "33016aad-b69d-45be-9359-82a41f556fd4"
DataPipes = "02685ad9-2d12-40c3-9f73-c6aeda6a7ff5"
IntervalSets = "8197267c-284f-5f27-9208-e0e47529a953"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
StructHelpers = "4093c41a-2008-41fd-82b8-e3f9d02b504f"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"
UnitfulAstro = "6112ee07-acf9-5e0f-b108-d242c714bf9f"

[weakdeps]
ComradeBase = "6d8c423b-a35f-4ef1-850c-862fe21f82c4"

[extensions]
ComradeBaseExt = "ComradeBase"

[compat]
AccessorsExtra = "0.1.77"
ComradeBase = "0.8.7, 0.9"
DataPipes = "0.3.17"
IntervalSets = "0.7"
LinearAlgebra = "1"
Random = "1"
StaticArrays = "1.1"
StructHelpers = "1.2.0"
Unitful = "1.6"
UnitfulAstro = "1.0"
julia = "1.6"
